PKG_NAME="mako"
PKG_VERSION="1.0.7"
PKG_LICENSE="MIT"
PKG_SITE="http://www.makotemplates.org/"
PKG_URL="https://files.pythonhosted.org/packages/source/M/Mako/Mako-$PKG_VERSION.tar.gz"
PKG_SOURCE_DIR="Mako-$PKG_VERSION"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Mako templates for Python"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="markupsafe"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
