PKG_NAME="cheetah"
PKG_VERSION="2.4.4"
PKG_LICENSE="MIT"
PKG_SITE="http://www.cheetahtemplate.org/"
PKG_URL="https://files.pythonhosted.org/packages/source/C/Cheetah/Cheetah-$PKG_VERSION.tar.gz"
PKG_SOURCE_DIR="Cheetah-$PKG_VERSION"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Cheetah, the Python-powered templating engine"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="markdown"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
