PKG_NAME="ipaddress"
PKG_VERSION="1.0.18"
PKG_LICENSE="PSFv2"
PKG_SITE="https://github.com/phihag/ipaddress"
PKG_URL="https://github.com/phihag/$PKG_NAME/archive/v$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Python 3.3's ipaddress for older Python versions"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
