PKG_NAME="hyperlink"
PKG_VERSION="17.3.1"
PKG_LICENSE="MIT"
PKG_SITE="https://github.com/python-hyper/hyperlink"
PKG_URL="https://github.com/python-hyper/$PKG_NAME/archive/v$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Immutable, Pythonic, correct URLs"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
