PKG_NAME="service_identity"
PKG_VERSION="17.0.0"
PKG_LICENSE="MIT"
PKG_SITE="https://service-identity.readthedocs.io/en/stable/"
PKG_URL="https://github.com/pyca/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Service identity verification for pyOpenSSL"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="attrs idna pyasn1 pyasn1-modules pyopenssl"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
