PKG_NAME="pyopenssl"
PKG_VERSION="17.3.0"
PKG_LICENSE="ASLv2"
PKG_SITE="https://pyopenssl.readthedocs.io/en/stable/"
PKG_URL="https://github.com/pyca/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="A Python wrapper around the OpenSSL library"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="cryptography six"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
