PKG_NAME="attrs"
PKG_VERSION="17.2.0"
PKG_LICENSE="MIT"
PKG_SITE="https://attrs.readthedocs.io/en/stable/"
PKG_URL="https://github.com/hynek/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Attributes without boilerplate"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
