PKG_NAME="six"
PKG_VERSION="1.11.0"
PKG_LICENSE="MIT"
PKG_SITE="http://pypi.python.org/pypi/six/"
PKG_URL="https://github.com/benjaminp/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain Python distutilscross:host"
PKG_LONGDESC="Python 2 and 3 compatibility utilities"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
