PKG_NAME="constantly"
PKG_VERSION="15.1.0"
PKG_LICENSE="MIT"
PKG_SITE="https://github.com/twisted/constantly"
PKG_URL="https://github.com/twisted/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Symbolic Constants in Python"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="attrs six"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
