PKG_NAME="markupsafe"
PKG_VERSION="1.0"
PKG_LICENSE="BSD"
PKG_SITE="http://github.com/pallets/markupsafe"
PKG_URL="https://github.com/pallets/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="A Python module that implements the jinja2.Markup string"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
