PKG_NAME="lxml"
PKG_VERSION="4.0.0"
PKG_LICENSE="BSD"
PKG_SITE="http://lxml.de/"
PKG_URL="https://github.com/lxml/$PKG_NAME/archive/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_SOURCE_DIR="lxml-$PKG_NAME-$PKG_VERSION"
PKG_DEPENDS_TARGET="toolchain cython:host libxslt:host Python libxml2 libxslt"
PKG_LONGDESC="The lxml XML toolkit for Python"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
