PKG_NAME="libtorrent"
PKG_VERSION="0.13.6"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/rakshasa/libtorrent"
PKG_URL="https://github.com/rakshasa/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain libressl zlib"
PKG_LONGDESC="libtorrent"
PKG_AUTORECONF="yes"

PKG_CONFIGURE_OPTS_TARGET="--enable-static --disable-debug --disable-shared"
