PKG_NAME="pyparsing"
PKG_VERSION="2.2.0"
PKG_LICENSE="MIT"
PKG_SITE="http://pyparsing.wikispaces.com/"
PKG_URL="https://files.pythonhosted.org/packages/source/p/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Python parsing module"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
