PKG_NAME="asn1crypto"
PKG_VERSION="0.23.0"
PKG_LICENSE="MIT"
PKG_SITE="https://github.com/wbond/asn1crypto"
PKG_URL="https://github.com/wbond/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Python ASN.1 library with a focus on performance and a pythonic API"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
