PKG_NAME="automat"
PKG_VERSION="0.6.0"
PKG_LICENSE="MIT"
PKG_SITE="https://github.com/glyph/automat"
PKG_URL="https://files.pythonhosted.org/packages/source/A/Automat/Automat-$PKG_VERSION.tar.gz"
PKG_SOURCE_DIR="Automat-$PKG_VERSION"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Self-service finite-state machines for the programmer on the go"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="attrs six"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
