PKG_NAME="pyasn1"
PKG_VERSION="0.3.6"
PKG_LICENSE="BSD"
PKG_SITE="https://github.com/etingof/pyasn1"
PKG_URL="https://github.com/etingof/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="ASN.1 library for Python"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
