PKG_NAME="python-gettext"
PKG_VERSION="3.0"
PKG_LICENSE="BSD"
PKG_SITE="https://pypi.python.org/pypi/python-gettext"
PKG_URL="https://github.com/hannosch/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Python Gettext po to mo file compiler"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
