PKG_NAME="pyasn1-modules"
PKG_VERSION="0.1.4"
PKG_LICENSE="BSD"
PKG_SITE="http://pyasn1.sourceforge.net/"
PKG_URL="http://downloads.sourceforge.net/project/pyasn1/$PKG_NAME/$PKG_VERSION/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Modules for ASN.1 library for Python"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="pyasn1"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
