PKG_NAME="pyasn1-modules"
PKG_VERSION="0.1.4"
PKG_LICENSE="BSD"
PKG_SITE="https://github.com/etingof/pyasn1-modules"
PKG_URL="https://github.com/etingof/$PKG_NAME/archive/v$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Modules for ASN.1 library for Python"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="pyasn1"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
