PKG_NAME="packaging"
PKG_VERSION="16.8"
PKG_LICENSE="APLv2"
PKG_SITE="https://github.com/pypa/packaging"
PKG_URL="https://github.com/pypa/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="Core utilities for Python packages"

PKG_IS_PYTHON="yes"
PKG_PYTHON_DEPENDS_TARGET="pyparsing six"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
