#!/bin/sh

. config/version

build_addons() {
  for clone in ${@:3}; do
    echo Cloning $clone/$2 from $1/$2
    ARCH=$2 PROJECT=$clone scripts/create_addon thoradia
    cp -ruv target/addons/$ADDON_VERSION/$1/$2/* target/addons/$ADDON_VERSION/$clone/$2
    echo
  done
}

tools/repo-tool -b thoradia S805

#build_addons Odroid_C2 aarch64 S905 S912
build_addons Odroid_C2 arm     S905 S912

tools/repo-tool -xml
