#!/bin/bash

. config/options "${1}"
if [ -f "${TARGET_IMG}/${ADDONS}/${ADDON_VERSION}/${DEVICE:-$PROJECT}/${TARGET_ARCH}/${PKG_ADDON_ID}/${PKG_ADDON_ID}-${ADDON_VERSION}.${PKG_REV}.zip" ]; then
  echo "Skipping ${DEVICE:-$PROJECT} ${1}"
else
  scripts/build "${1}"
  scripts/create_addon "${1}"
fi
