PKG_NAME="priority"
PKG_VERSION="1.3.0"
PKG_LICENSE="MIT"
PKG_SITE="http://python-hyper.org/priority/"
PKG_URL="https://files.pythonhosted.org/packages/source/p/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain distutilscross:host Python"
PKG_LONGDESC="A pure-Python implementation of the HTTP/2 priority tree"

PKG_IS_PYTHON="yes"
PKG_PYTHON_OPTS_TARGET="--cross-compile"
